2018-02-16 12:39:57,513 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:40:12,233 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:40:17,291 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:40:17,292 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26
2018-02-16 12:40:17,292 - GmailMassMailer - ERROR - please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:40:17,377 - GmailMassMailer - ERROR - unbound method save_error() must be called with error instance as first argument (got str instance instead)
2018-02-16 12:40:17,377 - GmailMassMailer - ERROR - unbound method save_error() must be called with error instance as first argument (got str instance instead)
Traceback (most recent call last):
  File "crawler.py", line 144, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 55, in login_to_gmail
    error.save_error(error_msg)
TypeError: unbound method save_error() must be called with error instance as first argument (got str instance instead)
2018-02-16 12:40:17,378 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:45:38,975 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:45:50,859 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:45:55,896 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:45:55,999 - GmailMassMailer - ERROR -  please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:45:56,000 - GmailMassMailer - ERROR - unbound method save_error() must be called with error instance as first argument (got str instance instead)
2018-02-16 12:45:56,000 - GmailMassMailer - ERROR - unbound method save_error() must be called with error instance as first argument (got str instance instead)
Traceback (most recent call last):
  File "crawler.py", line 143, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 54, in login_to_gmail
    error.save_error("error_msg")
TypeError: unbound method save_error() must be called with error instance as first argument (got str instance instead)
2018-02-16 12:45:56,000 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:47:21,423 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:47:24,055 - GmailMassMailer - ERROR - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:47:24,059 - GmailMassMailer - ERROR - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:47:24,059 - GmailMassMailer - ERROR - Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)
Traceback (most recent call last):
  File "crawler.py", line 144, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 50, in login_to_gmail
    self.driver.save_screenshot(LOG_PATH +user_name +'_login_error.png')
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 906, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 883, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 915, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 925, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:47:24,097 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:48:41,818 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:48:53,930 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:48:59,120 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:48:59,671 - GmailMassMailer - ERROR -  please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:49:00,197 - GmailMassMailer - ERROR - not enough arguments for format string
2018-02-16 12:49:00,197 - GmailMassMailer - ERROR - not enough arguments for format string
Traceback (most recent call last):
  File "crawler.py", line 144, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 55, in login_to_gmail
    err.save_error("error_msg")
  File "/home/duncan/workspace/GmailMassMailer/gmailmassmailer/model/dao.py", line 19, in save_error
    cur.execute("insert into error(detail,time_created) values('%s','%s',%d,%d)" %(msg,cur_time))
TypeError: not enough arguments for format string
2018-02-16 12:49:00,198 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:52:32,463 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:52:43,015 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:52:48,242 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:52:48,801 - GmailMassMailer - ERROR -  please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:53:00,157 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:57:44,089 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:57:53,924 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:57:59,137 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:57:59,721 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:58:10,864 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 12:59:22,562 - GmailMassMailer - INFO - Crawler started
2018-02-16 12:59:31,067 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 12:59:36,308 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 12:59:36,870 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 12:59:36,871 - GmailMassMailer - ERROR - cannot concatenate 'str' and 'NoSuchElementException' objects
2018-02-16 12:59:36,871 - GmailMassMailer - ERROR - cannot concatenate 'str' and 'NoSuchElementException' objects
Traceback (most recent call last):
  File "crawler.py", line 144, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 55, in login_to_gmail
    err.save_error(error_msg+' '+e)
TypeError: cannot concatenate 'str' and 'NoSuchElementException' objects
2018-02-16 12:59:36,871 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:00:36,752 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:00:52,728 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:00:57,974 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:00:58,538 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:00:58,538 - GmailMassMailer - ERROR - cannot concatenate 'str' and 'getset_descriptor' objects
2018-02-16 13:00:58,539 - GmailMassMailer - ERROR - cannot concatenate 'str' and 'getset_descriptor' objects
Traceback (most recent call last):
  File "crawler.py", line 144, in <module>
    log_in_susccesful=gmail.login_to_gmail()
  File "crawler.py", line 55, in login_to_gmail
    err.save_error(error_msg+' '+Exception.message)
TypeError: cannot concatenate 'str' and 'getset_descriptor' objects
2018-02-16 13:00:58,539 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:02:39,890 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:02:44,515 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:02:49,770 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:02:50,325 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:03:01,434 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:03:26,727 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:03:36,772 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:03:42,002 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:03:42,521 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:03:53,570 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:08:00,025 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:08:10,730 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:08:15,929 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:08:16,625 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:08:27,768 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:14:00,025 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:14:17,348 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:14:22,508 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:14:23,037 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:14:33,696 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:14:33,752 - GmailMassMailer - ERROR - [Errno 111] Connection refused
2018-02-16 13:14:33,752 - GmailMassMailer - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "crawler.py", line 153, in <module>
    gmail.open_url(start_url)
  File "crawler.py", line 62, in open_url
    self.driver.get(url)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 295, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
2018-02-16 13:14:33,825 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:16:20,404 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:16:42,706 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:16:47,934 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:16:48,443 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:16:59,062 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:17:04,125 - GmailMassMailer - ERROR - [Errno 111] Connection refused
2018-02-16 13:17:04,125 - GmailMassMailer - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "crawler.py", line 154, in <module>
    gmail.open_url(start_url)
  File "crawler.py", line 62, in open_url
    self.driver.get(url)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 295, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
2018-02-16 13:17:04,127 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:22:43,530 - GmailMassMailer - INFO - Crawler started
2018-02-16 13:22:55,693 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:23:00,912 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:23:01,412 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:23:11,968 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 13:23:31,197 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 13:23:36,412 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 13:23:36,968 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 13:23:48,051 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 18:38:11,500 - GmailMassMailer - INFO - Crawler started
2018-02-16 18:38:33,345 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 18:38:55,070 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 18:40:42,333 - GmailMassMailer - INFO - Crawler started
2018-02-16 18:41:00,648 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 18:43:11,750 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 18:43:36,912 - GmailMassMailer - INFO - Crawler started
2018-02-16 18:43:52,581 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 18:43:57,750 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 18:43:58,247 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 18:44:08,876 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-16 18:44:29,448 - GmailMassMailer - INFO - logging in to gmail
2018-02-16 18:44:34,646 - GmailMassMailer - ERROR - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="identifier"]"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.11.12-100.fc24.x86_64 x86_64)

2018-02-16 18:44:35,164 - GmailMassMailer - ERROR - Could not log in to gmail for account user: duncanndiithi password: elizabeth@wairimu26 please see error image at /home/duncan/workspace/GmailMassMailer/gmailmassmailer/service/logs/duncanndiithi_login_error.png
2018-02-16 18:46:36,323 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-19 16:09:03,529 - GmailMassMailer - INFO - Crawler started
2018-02-19 16:11:03,770 - GmailMassMailer - INFO - terminating gmailmassmailer crawler, shutting down web driver
2018-02-19 16:13:02,772 - GmailMassMailer - INFO - Crawler started
